name = "worker_rss"
main = "main.js"
compatibility_date = "2025-03-12"

[observability.logs]
enabled = true

[[kv_namespaces]]
binding = "RSS_KV"
id = "7573d0888204498baf9f91106b95ccf2" # 请替换为你的 KV Namespace ID，使用 `npx wrangler kv:namespace create RSS_KV` 创建

# 管理员密码配置（可选）
# 取消注释并设置密码以启用认证保护
 [vars]
 ADMIN_PASSWORD = "jD^wVuTF#e!nK1"

[[rules]]
type = "Text"
globs = ["**/*.html", "admin_style.css", "admin_script.js.txt"]
fallthrough = true



